version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: todo_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: todo_app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db/todo_db
      REDIS_URL: redis://todo_redis:6379/0
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
